In [2]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [4]:
df = (pd.read_csv('Data/50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend     Profit
21   7.838947       15.377343        29.973729  11.131302
37   4.406995        5.128314        19.702942   8.994914
2   15.344151       10.114555        40.793454  19.105039
14  11.994324       15.654742        25.651292  13.260265
44   2.217774       15.480614         2.833472   6.520033

In [ ]:
df = df.iloc[:,0:-1]
df

    R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37   4.406995        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       15.654742        25.651292
44   2.217774       15.480614         2.833472

In [8]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

C:\Users\ASUS\AppData\Local\Temp\ipykernel_27444\766688332.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
C:\Users\ASUS\AppData\Local\Temp\ipykernel_27444\766688332.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
C:\Users\ASUS\AppData\Local\Temp\ipykernel_27444\766688332.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan

In [9]:
df.head()

    R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37        NaN        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324             NaN        25.651292
44   2.217774       15.480614              NaN

In [10]:
df0 = pd.DataFrame()

In [ ]:
# Step1 : Replace with Mean
df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [14]:
df0

    R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37   9.348799        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.525207        25.651292
44   2.217774       15.480614        29.030354

In [15]:
# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37        NaN        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.525207        25.651292
44   2.217774       15.480614        29.030354

In [16]:
# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

    Administration  Marketing Spend
21       15.377343        29.973729
2        10.114555        40.793454
14       11.525207        25.651292
44       15.480614        29.030354

In [17]:
y = df1.iloc[[0,2,3,4],0]
y

21     7.838947
2     15.344151
14    11.994324
44     2.217774
Name: R&D Spend, dtype: float64

In [ ]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.02178743])

In [19]:
df1.iloc[1,0] = 23.14

In [20]:

df1

    R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  23.140000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.525207        25.651292
44   2.217774       15.480614        29.030354

In [21]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  23.140000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324             NaN        25.651292
44   2.217774       15.480614        29.030354

In [22]:
X = df1.iloc[[0,1,2,4],[0,2]]
X

    R&D Spend  Marketing Spend
21   7.838947        29.973729
37  23.140000        19.702942
2   15.344151        40.793454
44   2.217774        29.030354

In [23]:
y = df1.iloc[[0,1,2,4],1]
y

21    15.377343
37     5.128314
2     10.114555
44    15.480614
Name: Administration, dtype: float64

In [24]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.3823476])

In [25]:
df1.iloc[3,1] = 11.06
df1

    R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  23.140000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.060000        25.651292
44   2.217774       15.480614        29.030354

In [26]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  23.140000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.060000        25.651292
44   2.217774       15.480614              NaN

In [27]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

    R&D Spend  Administration
21   7.838947       15.377343
37  23.140000        5.128314
2   15.344151       10.114555
14  11.994324       11.060000

In [28]:

y = df1.iloc[0:4,-1]
y

21    29.973729
37    19.702942
2     40.793454
14    25.651292
Name: Marketing Spend, dtype: float64

In [29]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([27.33065522])

In [30]:

df1.iloc[4,-1] = 27.33

In [31]:

# After 1st Iteration
df1

    R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  23.140000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.060000        25.651292
44   2.217774       15.480614        27.330000

In [32]:
# Subtract 0th iteration from 1st iteration

df1 - df0

    R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37  13.791201        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000       -0.465207         0.000000
44   0.000000        0.000000        -1.700354

In [34]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

    R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37        NaN        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.060000        25.651292
44   2.217774       15.480614        27.330000

In [35]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([20.00343525])

In [36]:
df2.iloc[1,0] = 23.78

In [38]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.49950537])

In [39]:
df2.iloc[3,1] = 11.49

In [41]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([33.89079683])

In [43]:

df2.iloc[4,-1] = 33.89

df2

    R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  23.780000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.490000        25.651292
44   2.217774       15.480614        33.890000

In [44]:
df2 - df1

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37       0.64            0.00             0.00
2        0.00            0.00             0.00
14       0.00            0.43             0.00
44       0.00            0.00             6.56

In [46]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3

    R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37        NaN        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.490000        25.651292
44   2.217774       15.480614        33.890000

In [47]:

X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([25.44002706])

In [48]:
df3.iloc[1,0] = 25.44

In [50]:
df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.97067621])

In [51]:
df3.iloc[3,1] = 11.97

In [53]:

df3.iloc[4,-1] = np.nan
X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([52.44009567])

In [54]:
df3.iloc[4,-1] = 52.44

In [55]:

df2.iloc[3,1] = 11.22

In [56]:
df3

    R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  25.440000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.970000        25.651292
44   2.217774       15.480614        52.440000

In [57]:
df3 - df2

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37       1.66            0.00             0.00
2        0.00            0.00             0.00
14       0.00            0.75             0.00
44       0.00            0.00            18.55

## Using IterativeImputer class

In [59]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.experimental import enable_iterative_imputer  
from sklearn.impute import IterativeImputer

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [61]:
df = np.round(pd.read_csv('Data/50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [68]:
mask = np.random.rand(*df.shape) < 0.1  # 10% missing
df[mask] = np.nan

In [72]:
df.sample(5)

    R&D Spend  Administration  Marketing Spend  Profit
2         NaN            10.0             41.0    19.0
37        4.0             5.0             20.0     9.0
21        8.0            15.0             30.0    11.0
14        NaN             NaN             26.0    13.0
44        2.0            15.0              3.0     7.0

In [73]:
x_train = df.drop('Profit',axis=1)
y_train = df['Profit']

In [74]:
x_train,x_test,y_train,y_test = train_test_split(x_train,y_train,test_size=0.3,random_state=0)

In [75]:
# Step 1: Create IterativeImputer
imputer = IterativeImputer(estimator=LinearRegression(), random_state=0)

In [76]:
# Step 2: Fit the imputer on x_train only (never on x_test)
imputer.fit(x_train)

IterativeImputer(estimator=LinearRegression(), random_state=0)

In [78]:
x_train_imputed = imputer.transform(x_train)
x_test_imputed = imputer.transform(x_test)

lr=LinearRegression()

lr.fit(x_train_imputed,y_train)

y_pred=lr.predict(x_test_imputed)

r2_score(y_test,y_pred)

-101923304110.67178

i have created some missing value using Ai command that why it's showing this kind of result but our main purpose is to understand Iterativeclass implimentation