In [20]:
import numpy as np
import pandas as pd

In [21]:
date = pd.read_csv('Data/orders.csv')
time = pd.read_csv('Data/messages.csv')

In [22]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [23]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

# DATE

### First task change date dtype to datetime data type

In [24]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [26]:
date['date'] = pd.to_datetime(date['date'])

In [27]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1. Extract year

In [28]:
date['date_year'] = date['date'].dt.year

date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

## 2. Extract month

In [29]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [30]:
date['date_month'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year  date_month_no date_month
0 2019-12-10        5628       25       3       2019             12   December
1 2018-08-15        3646       14     157       2018              8     August
2 2018-10-23        1859       25       1       2018             10    October
3 2019-08-17        7292       25       1       2019              8     August
4 2019-01-06        4344       25       3       2019              1    January

## 3. Extract days

In [32]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [34]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,1,1
1,2018-08-15,3646,14,157,2018,8,August,2,2
2,2018-10-23,1859,25,1,2018,10,October,1,1
3,2019-08-17,7292,25,1,2019,8,August,5,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [37]:
# day of week - name
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,1,1,Tuesday
1,2018-08-15,2018,8,August,2,2,Wednesday
2,2018-10-23,2018,10,October,1,1,Tuesday
3,2019-08-17,2019,8,August,5,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [41]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,1,1,Tuesday,0
1,2018-08-15,2018,8,August,2,2,Wednesday,0
2,2018-10-23,2018,10,October,1,1,Tuesday,0
3,2019-08-17,2019,8,August,5,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

## 4. Extract week of the year

In [46]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,1,1,Tuesday,0,50
1,2018-08-15,2018,8,August,2,2,Wednesday,0,33
2,2018-10-23,2018,10,October,1,1,Tuesday,0,43
3,2019-08-17,2019,8,August,5,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

## 5. Extract Quarter

In [47]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,1,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,2,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,1,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,5,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

## 6. Extract Semester

In [48]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,1,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,2,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,1,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,5,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1


## 7. Extract Time elapsed between dates

In [49]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 6, 17, 14, 18, 29, 592062)

In [50]:

today - date['date']

0     2381 days 14:18:29.592062
1     2863 days 14:18:29.592062
2     2794 days 14:18:29.592062
3     2496 days 14:18:29.592062
4     2719 days 14:18:29.592062
                 ...
995   2809 days 14:18:29.592062
996   2750 days 14:18:29.592062
997   2598 days 14:18:29.592062
998   2663 days 14:18:29.592062
999   2437 days 14:18:29.592062
Name: date, Length: 1000, dtype: timedelta64[ns]

In [51]:
(today - date['date']).dt.days

0      2381
1      2863
2      2794
3      2496
4      2719
       ...
995    2809
996    2750
997    2598
998    2663
999    2437
Name: date, Length: 1000, dtype: int64

In [53]:
# Months passed

np.round((today - date['date']).dt.days / 30.44, 0)

0      78.0
1      94.0
2      92.0
3      82.0
4      89.0
       ...
995    92.0
996    90.0
997    85.0
998    87.0
999    80.0
Name: date, Length: 1000, dtype: float64

# TIME

In [54]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [55]:
time['date'] = pd.to_datetime(time['date'])

In [56]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [57]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0


## 1. Extract Time part

In [58]:

time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## 2. Time difference

In [59]:

today - time['date']

0     4567 days 13:28:29.592062
1     4431 days 14:38:29.592062
2     4917 days 13:57:29.592062
3     4219 days 13:47:29.592062
4     4616 days 15:07:29.592062
                 ...
995   5206 days 13:28:29.592062
996   4527 days 15:04:29.592062
997   4992 days 14:41:29.592062
998   5108 days 14:44:29.592062
999   4380 days 14:53:29.592062
Name: date, Length: 1000, dtype: timedelta64[ns]

In [60]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.946373e+08
1      3.828911e+08
2      4.248790e+08
3      3.645712e+08
4      3.988768e+08
           ...
995    4.498469e+08
996    3.911871e+08
997    4.313617e+08
998    4.413843e+08
999    3.784856e+08
Name: date, Length: 1000, dtype: float64

In [61]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.577288e+06
1      6.381518e+06
2      7.081317e+06
3      6.076187e+06
4      6.647947e+06
           ...
995    7.497448e+06
996    6.519784e+06
997    7.189361e+06
998    7.356404e+06
999    6.308093e+06
Name: date, Length: 1000, dtype: float64

In [62]:

# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      109621.474887
1      106358.641553
2      118021.958220
3      101269.791553
4      110799.124887
           ...
995    124957.474887
996    108663.074887
997    119822.691553
998    122606.741553
999    105134.891553
Name: date, Length: 1000, dtype: float64